stages:
  - deploy

deploy-job:
  stage: deploy
  before_script:
    # Setup SSH
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa

    # Add GitLab + EC2 to known hosts
    - ssh-keyscan -H gitlab.com >> ~/.ssh/known_hosts
    - ssh-keyscan -H 54.236.241.188 >> ~/.ssh/known_hosts

  script:
    - ssh ec2-user@54.236.241.188 "
        echo '🚀 Starting Deployment' &&
        rm -rf reactinternaldocker &&
        git clone -b master git@gitlab.com:RIMaheshKumar/reactinternaldocker.git &&
        cd reactinternaldocker &&
        docker build -t reactdocker-app . &&
        docker stop reactdocker-app || true &&
        docker rm reactdocker-app || true &&
        docker run -d -p 80:80 --name reactdocker-app reactdocker-app &&
        echo '✅ Deployment Completed'
      "